# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 179eb20dbb6b1abf09b9464068813e655132812af0b90d4dd8dced504144b7f2cf87ac30bfcdd1aee7c2bb0db1093c8c995539f5c3d63c6c2fa567f48e2d67de

test:
  secret_key_base: e2a0ec453f8ce36030fb4143bd0986940d5734ea41ee4c72f461cf87cf4ea0e63fb63aca7237a62840b25e0a35378f463467a421f88ad8dd55504fbb57109cb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
